apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantkart-frontend
  namespace: plantkart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plantkart-frontend
  template:
    metadata:
      labels:
        app: plantkart-frontend
    spec:
      containers:
      - name: frontend
        image: <ACCOUNT>.dkr.ecr.<REGION>.amazonaws.com/plantkart-frontend:latest
        ports:
        - containerPort: 80
