apiVersion: v1
kind: Secret
metadata:
  name: plantkart-secret
  namespace: plantkart
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:postgres@postgres.plantkart.svc.cluster.local:5432/plantkartdb
  JWT_SECRET: replace-me
  STRIPE_SECRET_KEY: sk_live_replace
  CLIENT_BASE_URL: https://shop.example.com
